#!/usr/bin/env python3
"""
TestSprite MCP Test Suite Summary Generator

Generates a comprehensive summary of all test categories and coverage.
"""

import json
import os
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime


def collect_test_results(test_dir: Path) -> Dict[str, Any]:
    """Collect results from all test reports"""
    
    results = {
        "timestamp": datetime.now().isoformat(),
        "categories": {},
        "summary": {
            "total_tests": 0,
            "total_passed": 0,
            "total_failed": 0,
            "categories_tested": 0,
            "categories_passed": 0
        }
    }
    
    # Find all test report files
    report_files = list(test_dir.glob("testsprite_report_*.json"))
    
    for report_file in report_files:
        try:
            with open(report_file, 'r') as f:
                data = json.load(f)
                
            category = data.get('summary', {}).get('category', 'unknown')
            
            results["categories"][category] = {
                "total": data['summary']['total_tests'],
                "passed": data['summary']['passed'],
                "failed": data['summary']['failed'],
                "success_rate": data['summary']['success_rate'],
                "duration": data['summary']['total_duration'],
                "status": data['summary']['status']
            }
            
            results["summary"]["total_tests"] += data['summary']['total_tests']
            results["summary"]["total_passed"] += data['summary']['passed']
            results["summary"]["total_failed"] += data['summary']['failed']
            results["summary"]["categories_tested"] += 1
            
            if data['summary']['status'] == 'PASSED':
                results["summary"]["categories_passed"] += 1
                
        except Exception as e:
            print(f"Warning: Could not parse {report_file}: {e}")
    
    # Calculate overall success rate
    if results["summary"]["total_tests"] > 0:
        results["summary"]["overall_success_rate"] = (
            results["summary"]["total_passed"] / results["summary"]["total_tests"] * 100
        )
    else:
        results["summary"]["overall_success_rate"] = 0
    
    return results


def generate_markdown_summary(results: Dict[str, Any]) -> str:
    """Generate markdown summary report"""
    
    summary = results["summary"]
    
    md = f"""# TestSprite MCP Test Suite Summary

**Generated:** {results['timestamp']}

## [STATS] Overall Results

| Metric | Value |
|--------|-------|
| **Total Tests** | {summary['total_tests']} |
| **Passed** | {summary['total_passed']} [OK] |
| **Failed** | {summary['total_failed']} [FAIL] |
| **Success Rate** | {summary['overall_success_rate']:.1f}% |
| **Categories** | {summary['categories_tested']} |
| **Categories Passed** | {summary['categories_passed']} |

## [FILE] Category Breakdown

"""
    
    for category, data in sorted(results["categories"].items()):
        status_icon = "[OK]" if data['status'] == 'PASSED' else "[FAIL]"
        md += f"""### {category.upper()} {status_icon}

- **Tests:** {data['total']}
- **Passed:** {data['passed']} ({data['success_rate']:.1f}%)
- **Failed:** {data['failed']}
- **Duration:** {data['duration']:.2f}s

"""
    
    md += """## [TARGET] Coverage Analysis

### Target vs Actual

| Category | Target | Actual | Status |
|----------|--------|--------|--------|
| Core (TC*) | 95% | TBD | [WARNING] |
| Edge Cases (EC*) | 90% | TBD | [WARNING] |
| Error Handling (EH*) | 95% | TBD | [WARNING] |
| Security (SC*) | 90% | TBD | [WARNING] |
| Performance (PF*) | 80% | TBD | [WARNING] |
| Regression (RG*) | 100% | TBD | [WARNING] |

## [INFO] Notes

- All test categories have been implemented and executed
- Edge case coverage includes input validation, boundaries, concurrency, data limits, special characters, and timezone handling
- Error handling covers network, API, database, AI services, authentication, and validation errors
- Security tests include SQL injection, XSS, auth bypass, and rate limiting
- Performance tests validate response times, concurrent users, and memory usage
- Regression tests ensure critical user journeys remain functional

---

*Generated by TestSprite MCP Test Suite*
"""
    
    return md


def main():
    """Main entry point"""
    test_dir = Path(__file__).parent
    
    print("Collecting test results...")
    results = collect_test_results(test_dir)
    
    # Generate summary
    md_report = generate_markdown_summary(results)
    
    # Save report
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = test_dir / f"test_suite_summary_{timestamp}.md"
    
    with open(report_path, 'w') as f:
        f.write(md_report)
    
    print(f"\nSummary saved to: {report_path}")
    
    # Print summary to console
    print("\n" + "="*70)
    print("TEST SUITE SUMMARY")
    print("="*70)
    print(f"Total Tests: {results['summary']['total_tests']}")
    print(f"Passed: {results['summary']['total_passed']} [OK]")
    print(f"Failed: {results['summary']['total_failed']} [FAIL]")
    print(f"Success Rate: {results['summary']['overall_success_rate']:.1f}%")
    print(f"Categories: {results['summary']['categories_tested']}")
    print("="*70)


if __name__ == "__main__":
    main()
