import React from 'react';
import { motion } from 'framer-motion';
import type { BrandIdentityData } from '../types';
import { useLanguage } from '../context/LanguageContext';

const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.1 } },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
};

const BrandIdentityDisplay: React.FC<{ data: BrandIdentityData }> = ({
  data,
}) => {
  const { t } = useLanguage();

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="w-full space-y-8 max-w-4xl mx-auto"
    >
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Logo Section */}
        <motion.div
          variants={itemVariants}
          className="bg-brand-secondary/30 rounded-xl p-6 flex flex-col items-center justify-center border border-brand-accent/30 shadow-lg"
        >
          <h3 className="text-2xl font-bold text-brand-teal mb-4 text-center">
            Visual Identity Concept
          </h3>
          <div className="relative w-full aspect-square max-w-sm bg-brand-primary/50 rounded-lg overflow-hidden border border-white/10 shadow-inner mb-4 group">
            <img
              src={data.logoImage}
              alt="AI Generated Logo"
              className="w-full h-full object-contain p-4"
            />
            <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
              <a
                href={data.logoImage}
                download="atlas-logo-concept.jpg"
                className="px-4 py-2 bg-brand-teal hover:bg-teal-500 text-white rounded-full font-bold shadow-lg transform hover:scale-105 transition-all"
              >
                Download
              </a>
            </div>
          </div>
          <p className="text-xs text-brand-light/50 text-center font-mono">
            Generated by Imagen 3
          </p>
        </motion.div>

        {/* Strategy Section */}
        <div className="space-y-6">
          {/* Palette */}
          <motion.div
            variants={itemVariants}
            className="bg-brand-secondary/30 rounded-xl p-6 border border-brand-accent/30"
          >
            <h4 className="text-lg font-bold text-brand-light mb-4">
              Color Palette
            </h4>
            <div className="flex gap-2 justify-center md:justify-start">
              {data.palette.map((color, index) => (
                <div key={index} className="group relative">
                  <div
                    className="w-12 h-12 rounded-full border-2 border-white/10 shadow-md cursor-pointer transform hover:scale-110 transition-all"
                    style={{ backgroundColor: color }}
                  ></div>
                  <span className="absolute -bottom-6 left-1/2 -translate-x-1/2 text-xs font-mono text-brand-light opacity-0 group-hover:opacity-100 transition-opacity">
                    {color}
                  </span>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Rationale */}
          <motion.div
            variants={itemVariants}
            className="bg-brand-secondary/30 rounded-xl p-6 border border-brand-accent/30 flex-grow"
          >
            <h4 className="text-lg font-bold text-brand-light mb-2">
              Design Rationale
            </h4>
            <p className="text-brand-text/90 leading-relaxed text-sm">
              {data.rationale}
            </p>
          </motion.div>

          {/* Prompt Details (Collapsible/Small) */}
          <motion.div
            variants={itemVariants}
            className="p-4 rounded-lg bg-black/20 border border-brand-accent/20"
          >
            <p className="text-xs font-bold text-brand-accent mb-1 uppercase tracking-wider">
              Image Prompt Used
            </p>
            <p className="text-xs text-brand-light/70 font-mono italic line-clamp-3 hover:line-clamp-none transition-all cursor-help">
              "{data.imagePrompt}"
            </p>
          </motion.div>
        </div>
      </div>
    </motion.div>
  );
};

export default BrandIdentityDisplay;
